### ISSUE TITLE
Allow to mint RAY token with zero value

### ISSUE THREAD

**Issue by pash7ka** [Stakedllc/robo-advisor-yield#16]
In a smart-contract system I'm writing, i would preffer if i can do this way:
1. During my contract deploy & initialization it mints a new RAY token
2. When funds added to my contract it deposits them to RAY with already exisiting tokenId

Currently this is not possible, because minting RAY token requires non-zero deposit.
This is checked at [PositionManager.verifyAmount](https://github.com/Stakedllc/robo-advisor-yield/blob/master/contracts/ray/protocol/impl/PositionManager.sol#L103) modifier

```solidity
    require(
        value > _storage.getMinAmount(principalAddress),
        "#PositionManager verifyAmount Modifier: Cannot add or withdraw less than the minimum amount"
    );
```
Please note, currently nothing prevents one to mint a token and then withdraw the whole deposit without burning the token.
Also please note, that error description only denies amounts less then the minimum, which does not match with condition which requires amount to be strictly greater than the minimum.

I propose to change this check:
```solidity
    require(
        value == 0 || value >= _storage.getMinAmount(principalAddress),
        "#PositionManager verifyAmount Modifier: Cannot add or withdraw less than the minimum amount"
    );
```
Implementing this feature will save me from cheking rayTokenId value in each deposit, which will save some gas.

**Comment by dpurhar27** [comment]
Hi @pash7ka !

Thanks for submitting this feature request.

This is good feedback relating to the error message not matching the conditional - this should be updated in the next release.

You are correct - it's an existing feature that one can mint a new token and withdraw all it's value, leaving the shell of the token behind to be potentially re-used.

The `minAmount` check was added to help catch user blunder, where they enter the wrong units as a parameter, and mint a token with no or next to no value without realizing it. 

For your use-case, is it possible to mint a RAY token (with nominal value) before deploying the contract? Such as: mint the RAY token -> deploy the contract -> as a part of the constructor have parameter `rayTokenId`, and `transferFrom()` the RAY token corresponding to the specified ID? 
This way, you still have a trust-less solution, and no longer need to check to see if `rayTokenId` is null, saving on gas.

**Comment by pash7ka** [comment]
Hi @dpurhar27 !
Thanks for fast reply!
In the project I'm working on, we need to deposit and withdraw DAI from RAY during contract life time.
Actually, I've already [implemented](https://github.com/akropolisio/akropolisOS/blob/feature/defi-ray/contracts/modules/defi/RAYModule.sol#L32) it with the "if" approach. And to be honest, i believe this "if" does not add too much gas compared with the whole workflow.
Still, it would be nice if i could save at least something.

**Comment by dpurhar27** [comment]
Ok cool - good to hear, and yes, the `if()` is relatively cheap. 

I'll close this issue when the error message/condition is corrected to match each other. Thanks again for raising this point!
